language: java
jdk: oraclejdk8
before_install:
- chmod +x gradlew
before_deploy:
- chmod ugo+x deploy.sh
script:
- ./gradlew wrapper
- ./gradlew clean build
- ./gradlew warNoStatic warCopy zipGetVersion zipStatic
- sh ./deploy_travisci.sh
env:
  global:
  - GH_REF: github.com/krishnaprasad/spring-music.git
  - COMMIT_AUTHOR_EMAIL: krishnaprasad.t@gmail.com
